package org.omg.PortableServer;


/**
* org/omg/PortableServer/LIFESPAN_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from d:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u77/6540/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Sunday, March 20, 2016 10:02:51 PM PDT
*/

public interface LIFESPAN_POLICY_ID
{

  /**
	 * The value representing LIFESPAN_POLICY_ID.
	 */
  public static final int value = (int)(17L);
}
